### ISSUE TITLE
.idea Folder should not be in the git

### ISSUE THREAD

**Issue by grimsi** [Kapparov/Filmdatenbank#2]
Use a .gitignore file to exlude certain configuration folders like ".idea".
There are many plugins available for IntelliJ Idea that support this

**Comment by Kapparov** [comment]
OK wird im nächsten commit gemacht.

**Comment by Kapparov** [comment]
Done.

**Comment by grimsi** [comment]
Not done.
Various config files are still in the repository (e.g. Filmdatenbank.iml)
